version: "3.8"

services:
  web:
    image: nginx:latest
    container_name: my_web
    ports:
       - 8080:80
    volumes:
       - ./mywebsite:/usr/share/nginx/html
    command: nginx -g "daemon off;"
