version: "3.8"
services:
  app:
     image: php:7.4-apache
     container_name: app
     ports:
      - 8080:80
     volumes:
      - ./app:/var/www/html
     command: >
      bash -c "docker-php-ext-install mysqli &&
      apache2-foreground"
     depends_on:
      - db
  db:
     image: mysql:5.7
     container_name: db
     volumes:
      - sql_data:/var/lib/mysql
     environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
volumes:
  sql_data:
