services:
  frontend:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/html:/usr/share/nginx/html
    networks:
      - frontend_network
  api:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ./api:/app
    command: sh -c "pip install -r requirements.txt && python app.py"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - frontend_network
      - backend_network
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgressql/data
    networks:
      - backend_network

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge

volumes:
  db_data:
