version: '3'
services:
  web:
    image: nginx:${NGINX_VERSION}
    container_name: web
    ports:
      - ${WEB_PORT}:80
    volumes:
      - .html:/usr/share/nginx/html

  db:
    image: mysql:${MYSQL_VERSION}
    container_name: db
    ports:
     - ${MYSQL_PORT}:3306
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
     - mysql-data:/var/lib/mysql


volumes:
  mysql-data:

