version: '3'
services:
  web:
    image: nginx:alpine
    networks:
      - public_network
      - app_network
  api:
    image: python:3.9-alpine
    command: tail -f /dev/null
    networks:
      - app_network
      - db_network

  db:
    image: postgres:13-alpine
    networks:
      - db_network

  cache:
    image: redis:alpine
    networks:
      - db_network

networks:
  public_network:
    external: true
  app_network:
    driver: bridge
  db_network:
    driver: bridge
