version: "3"
services:
  web_server:
    image: nginx:latest
    container_name: dev-web
    ports:
      - 8000:80
    volumes:
      - ./src:/usr/share/nginx/html
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: dev-db
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=devpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminpanel:
    image: adminer:latest
    container_name: dev-adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data:

