version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: web
    networks:
      - frontend_network


  api:
    image: alpine
    container_name: api
    command: tail -f /dev/null
    networks:
      - frontend_network
      - backend_network

  db:
    image: postgres:alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=test
    networks:
      - backend_network

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge

